package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "messages")
data class MessageEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val text: String,
    val category: String, // e.g., "Pickup Lines", "Love Messages", "Conversation Starters", "Compliments", "Breakup Messages", "Apology Messages", "Anniversary Wishes"
    val subcategory: String, // e.g., "Funny", "Cute", "Good Morning", etc.
    val language: String, // e.g., "English", "বাংলা", "हिन्दी", "العربية", "Español", "Français", "Deutsch", "Português", "Italiano"
    val mood: String, // e.g., "Happy", "Romantic", "Funny", "Shy", "Confident"
    val occasion: String, // e.g., "Birthday", "First Date", "Valentine's Day", "Anniversary", "None"
    val isFavorite: Boolean = false,
    val isCustom: Boolean = false, // True if generated by AI or custom added by user
    val collectionName: String? = null, // Custom bookmark collection name if categorized
    val isRead: Boolean = false, // Track if read for achievements
    val shareCount: Int = 0, // Track shares for achievements
    val copyCount: Int = 0, // Track copies for achievements
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "bookmark_collections")
data class BookmarkCollectionEntity(
    @PrimaryKey val name: String,
    val colorHex: String,
    val iconName: String,
    val timestamp: Long = System.currentTimeMillis()
)

@Entity(tableName = "activity_logs")
data class ActivityLogEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val type: String, // "copy", "share", "read", "favorite", "ai_generate"
    val messageId: Int,
    val timestamp: Long = System.currentTimeMillis()
)
